spring:

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://dev-1wrhewbsoopiootw.us.auth0.com/


server:
  error:
    include-stacktrace: never

auth0:
  audience: https://phrase-api
