spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phrase-api
    username: root
    password: mcdo4ever
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-1wrhewbsoopiootw.us.auth0.com/


server:
  error:
    include-stacktrace: never

auth0:
  audience: https://phrase-api
